'use client'

import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, ArrowRight, Check, ChevronDown, Hotel, Landmark, MapPin, Plane, Route, Sparkles } from 'lucide-react'
import { useLocale } from '@/components/i18n'
import styles from './travel-request-center.module.css'

type Service = 'flight' | 'hotel' | 'visa' | 'umrah' | 'transfer' | 'custom'
type Values = Record<string, string | number | boolean>
type Errors = Record<string, string>
type FieldValue = string | number | boolean
type Segment = { from: string; to: string; date: string }
type RequestResult = { ok: boolean; reference?: string; message?: string }

const services: { id: Service; en: string; ar: string; icon: typeof Plane }[] = [
  { id: 'flight', en: 'Flights', ar: 'الطيران', icon: Plane },
  { id: 'hotel', en: 'Hotels', ar: 'الفنادق', icon: Hotel },
  { id: 'visa', en: 'Visa Services', ar: 'خدمات التأشيرات', icon: Landmark },
  { id: 'umrah', en: 'Hajj & Umrah', ar: 'الحج والعمرة', icon: Sparkles },
  { id: 'transfer', en: 'Transfers', ar: 'الانتقالات', icon: MapPin },
  { id: 'custom', en: 'Custom Travel', ar: 'طلب سفر مخصص', icon: Route },
]

const copy = {
  en: {
    eyebrow: 'LEGENDARY MANAGEMENT MEA', title: 'What can we arrange for you?', intro: 'Choose the service you need and provide the trip details. Our team will review your request and coordinate the next steps.',
    steps: ['Service', 'Travel details', 'Contact', 'Review'], next: 'Continue', back: 'Back', submit: 'Submit request', another: 'Submit another request', home: 'Back to home', required: 'Please complete this field.', invalidEmail: 'Enter a valid email address.', dateOrder: 'The end date must be after the start date.', unavailable: 'Your request is complete, but the secure receiving channel is not configured yet. Please contact our team directly.',
    received: 'Request received.', receivedBody: 'Our team will review the details and contact you regarding the next steps.', select: 'Choose a service', details: 'Travel details', contact: 'Contact information', review: 'Review your request', editDetails: 'Edit travel details', editContact: 'Edit contact details', optional: 'Optional', yes: 'Yes', no: 'No', addFlight: '+ Add another flight', remove: 'Remove', nights: 'nights', disclaimer: 'Visa approval remains subject to the relevant embassy, consulate, immigration authority, and applicable regulations.',
  },
  ar: {
    eyebrow: 'ليجندري مانجمنت الشرق الأوسط وأفريقيا', title: 'وش الخدمة اللي تحتاج نرتّبها؟', intro: 'اختر الخدمة وأضف تفاصيل الرحلة المتوفرة. يراجع فريقنا الطلب ويتواصل معك لتنسيق الخطوات التالية.',
    steps: ['الخدمة', 'تفاصيل السفر', 'بيانات التواصل', 'مراجعة الطلب'], next: 'متابعة', back: 'رجوع', submit: 'إرسال الطلب', another: 'إرسال طلب آخر', home: 'العودة للرئيسية', required: 'هذا الحقل مطلوب.', invalidEmail: 'أدخل بريدًا إلكترونيًا صحيحًا.', dateOrder: 'يجب أن يكون تاريخ النهاية بعد تاريخ البداية.', unavailable: 'تفاصيل الطلب مكتملة، لكن قناة الاستقبال الآمنة غير مهيأة حاليًا. تواصل مباشرة مع فريقنا.',
    received: 'استلمنا طلبك.', receivedBody: 'يراجع فريقنا التفاصيل ويتواصل معك بخصوص الخطوات التالية.', select: 'اختر الخدمة', details: 'تفاصيل السفر', contact: 'بيانات التواصل', review: 'راجع طلبك', editDetails: 'تعديل تفاصيل السفر', editContact: 'تعديل بيانات التواصل', optional: 'اختياري', yes: 'نعم', no: 'لا', addFlight: '+ إضافة رحلة', remove: 'حذف', nights: 'ليالٍ', disclaimer: 'تخضع الموافقة على التأشيرة للجهة المختصة من سفارة أو قنصلية أو إدارة هجرة وللأنظمة المعمول بها.',
  },
}

const initial: Values = { tripType: 'round', adults: 1, children: 0, infants: 0, rooms: 1, contactMethod: 'whatsapp', flexible: false, directOnly: false, airportTransfer: false, transferType: 'airport-hotel', programType: 'umrah', packageType: 'complete' }

export function TravelRequestCenter() {
  const { locale } = useLocale(); const ar = locale === 'ar'; const c = copy[locale]
  const query = useSearchParams(); const requested = query.get('service') as Service | null
  const requestedService = services.some(s => s.id === requested) ? requested : null
  const firstService = requestedService || 'flight'
  const [service, setService] = useState<Service>(firstService); const [step, setStep] = useState(requested ? 1 : 0)
  const [values, setValues] = useState<Values>(initial); const [segments, setSegments] = useState([{ from: '', to: '', date: '' }, { from: '', to: '', date: '' }])
  const [errors, setErrors] = useState<Errors>({}); const [sending, setSending] = useState(false); const [result, setResult] = useState<RequestResult | null>(null)
  const set = (name: string, value: FieldValue) => { setValues(v => ({ ...v, [name]: value })); setErrors(e => ({ ...e, [name]: '' })) }
  const activeService = requestedService || service
  const selected = services.find(s => s.id === activeService)!
  useEffect(() => {
    if (requested && services.some(s => s.id === requested)) {
      setService(requested)
      setStep(1)
      setErrors({})
    }
  }, [requested])
  useEffect(() => { void fetch('/api/travel-requests', { method: 'GET', cache: 'no-store' }) }, [])
  const nights = useMemo(() => { const a = new Date(String(values.checkIn || '')); const b = new Date(String(values.checkOut || '')); return a && b && b > a ? Math.ceil((+b - +a) / 86400000) : 0 }, [values.checkIn, values.checkOut])
  const requiredByService: Record<Service, string[]> = { flight: values.tripType === 'multi' ? [] : ['origin','destination','departureDate'], hotel: ['hotelDestination','checkIn','checkOut'], visa: ['visaCountry','nationality','residence','travelDate'], umrah: ['departureCity','travelDate'], transfer: ['pickup','dropoff','pickupDate','pickupTime'], custom: ['customDestination','startDate','endDate','tripBrief'] }
  const labels = fieldLabels(ar)
  const validate = (target: number) => {
    const next: Errors = {}; const required = target >= 2 ? ['fullName','email','phone','residenceCountry'] : requiredByService[activeService]
    required.forEach(k => { if (!String(values[k] ?? '').trim()) next[k] = c.required })
    if (target >= 2 && values.email && !/^\S+@\S+\.\S+$/.test(String(values.email))) next.email = c.invalidEmail
    const pairs = activeService === 'hotel' ? [['checkIn','checkOut']] : activeService === 'custom' ? [['startDate','endDate']] : activeService === 'visa' ? [['travelDate','returnDate']] : values.tripType === 'round' ? [['departureDate','returnDate']] : []
    pairs.forEach(([a,b]) => { if (values[a] && values[b] && new Date(String(values[b])) <= new Date(String(values[a]))) next[b] = c.dateOrder })
    if (activeService === 'flight' && values.tripType === 'multi' && segments.some(x => !x.from || !x.to || !x.date)) next.segments = c.required
    setErrors(next); return !Object.keys(next).length
  }
  const advance = () => { if (step === 0) setStep(1); else if (step === 1 && validate(1)) setStep(2); else if (step === 2 && validate(2)) setStep(3) }
  const submit = async () => {
    if (!validate(2)) { setStep(2); return }
    setSending(true); setResult(null)
    try { const response = await fetch('/api/travel-requests', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ serviceType: activeService, locale, contact: pick(values, ['fullName','company','email','phone','residenceCountry','contactMethod']), payload: { ...values, segments: values.tripType === 'multi' ? segments : undefined }, website: values.website || '' }) }); const data = await response.json(); setResult(response.ok ? { ok: true, reference: data.reference } : { ok: false, message: data.message || c.unavailable }) } catch { setResult({ ok: false, message: c.unavailable }) } finally { setSending(false) }
  }
  if (result?.ok) return <section className={styles.success} dir={ar ? 'rtl' : 'ltr'}><span><Check /></span><div className="section-kicker">{ar ? 'تم الإرسال' : 'REQUEST CONFIRMED'}</div><h1>{c.received}</h1><p>{c.receivedBody}</p>{result.reference && <strong dir="ltr">{result.reference}</strong>}<div><Link href="/" className="button button-navy">{c.home}</Link><button className="button button-gold" onClick={() => { setValues(initial); setStep(0); setResult(null) }}>{c.another}</button></div></section>
  return <div className={styles.page} dir={ar ? 'rtl' : 'ltr'}>
    <section className={styles.hero}><div className="section-shell"><div className="section-kicker">{c.eyebrow}</div><h1>{c.title}</h1><p>{c.intro}</p></div></section>
    <section className={`${styles.workspace} section-shell`}>
      <nav className={styles.progress} aria-label={ar ? 'مراحل الطلب' : 'Request progress'}>{c.steps.map((label, i) => <button key={label} type="button" className={i === step ? styles.current : i < step ? styles.done : ''} onClick={() => i < step && setStep(i)} disabled={i > step}><span>{i < step ? <Check size={15}/> : `0${i + 1}`}</span><b>{label}</b></button>)}</nav>
      <div className={styles.frame}>
        <aside className={styles.aside}><span>{`0${step + 1}`} / 04</span><h2>{[c.select,c.details,c.contact,c.review][step]}</h2><p>{ar ? 'أضف المعلومات المتوفرة فقط. يراجع الفريق التفاصيل قبل أي تأكيد.' : 'Add the information available now. The team reviews the details before any confirmation.'}</p><div className={styles.asideService}><selected.icon/><small>{ar ? selected.ar : selected.en}</small></div></aside>
        <div className={styles.formPanel}>
          {step === 0 && <ServiceSelector service={service} setService={id => { setService(id); setErrors({}) }} ar={ar}/>}
          {step === 1 && <div className={styles.fields}><ServiceFields service={activeService} values={values} set={set} ar={ar} errors={errors} labels={labels} segments={segments} setSegments={setSegments} nights={nights}/></div>}
          {step === 2 && <div className={styles.fields}><SectionHeading index="01" title={ar ? 'بيانات المسؤول عن الطلب' : 'Request contact'}/><Field name="fullName" label={labels.fullName} value={values.fullName} set={set} error={errors.fullName}/><Field name="company" label={`${labels.company} — ${c.optional}`} value={values.company} set={set}/><Field name="email" type="email" label={labels.email} value={values.email} set={set} error={errors.email}/><Field name="phone" type="tel" label={labels.phone} value={values.phone} set={set} error={errors.phone}/><Field name="residenceCountry" label={labels.residenceCountry} value={values.residenceCountry} set={set} error={errors.residenceCountry}/><Select name="contactMethod" label={labels.contactMethod} value={values.contactMethod} set={set} options={opts(ar, [['whatsapp','WhatsApp','واتساب'],['phone','Phone','اتصال هاتفي'],['email','Email','بريد إلكتروني']])}/><input className={styles.honeypot} tabIndex={-1} autoComplete="off" name="website" aria-hidden="true" value={String(values.website || '')} onChange={e => set('website', e.target.value)}/></div>}
          {step === 3 && <Review service={activeService} values={values} segments={segments} ar={ar} labels={labels} onDetails={() => setStep(1)} onContact={() => setStep(2)} result={result}/>}
          <div className={styles.actions}>{step > 0 && <button type="button" className={styles.back} onClick={() => setStep(s => s - 1)}>{ar ? <ArrowRight/> : <ArrowLeft/>}{c.back}</button>}<div/>{step < 3 ? <button type="button" className="button button-navy" onClick={advance}>{c.next}{ar ? <ArrowLeft size={17}/> : <ArrowRight size={17}/>}</button> : <button type="button" className="button button-gold" disabled={sending} onClick={submit}>{sending ? (ar ? 'جارٍ الإرسال…' : 'Submitting…') : c.submit}</button>}</div>
        </div>
      </div>
    </section>
  </div>
}

function ServiceSelector({ service, setService, ar }: { service: Service; setService: (s: Service) => void; ar: boolean }) { return <div className={styles.selector}>{services.map((s,i) => { const Icon=s.icon; return <button type="button" aria-pressed={service===s.id} className={service===s.id?styles.active:''} onClick={() => setService(s.id)} key={s.id}><span>0{i+1}</span><Icon/><strong>{ar?s.ar:s.en}</strong><i/></button> })}</div> }
function SectionHeading({ index, title, note }: { index: string; title: string; note?: string }) { return <div className={styles.sectionHeading}><span>{index}</span><div><h3>{title}</h3>{note&&<p>{note}</p>}</div></div> }
function Field({ name,label,value,set,type='text',error,min }: { name:string;label:string;value:unknown;set:(n:string,v:string)=>void;type?:string;error?:string;min?:string }) { return <label className={styles.field}><span>{label}</span><input name={name} type={type} min={min || (type==='date'?new Date().toISOString().slice(0,10):undefined)} value={String(value??'')} onChange={e=>set(name,e.target.value)} aria-invalid={!!error} aria-describedby={error?`${name}-error`:undefined}/>{error&&<small id={`${name}-error`}>{error}</small>}</label> }
function Select({name,label,value,set,options,error}:{name:string;label:string;value:unknown;set:(n:string,v:string)=>void;options:[string,string][];error?:string}) { return <label className={styles.field}><span>{label}</span><div className={styles.select}><select value={String(value??'')} onChange={e=>set(name,e.target.value)} aria-invalid={!!error}><option value="">—</option>{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><ChevronDown/></div>{error&&<small>{error}</small>}</label> }
function NumberField({name,label,value,set,min=0}:{name:string;label:string;value:unknown;set:(n:string,v:number)=>void;min?:number}) { return <label className={styles.field}><span>{label}</span><input type="number" min={min} value={Number(value??0)} onChange={e=>set(name,Math.max(min,+e.target.value))}/></label> }
function Toggle({name,label,value,set}:{name:string;label:string;value:unknown;set:(n:string,v:boolean)=>void}) { return <label className={styles.toggle}><input type="checkbox" checked={!!value} onChange={e=>set(name,e.target.checked)}/><span/><b>{label}</b></label> }
function Choice({name,label,value,set,options}:{name:string;label:string;value:unknown;set:(n:string,v:string)=>void;options:[string,string][]}) { return <fieldset className={styles.choice}><legend>{label}</legend><div>{options.map(([v,l])=><label key={v}><input type="radio" name={name} value={v} checked={value===v} onChange={()=>set(name,v)}/><span>{l}</span></label>)}</div></fieldset> }

function ServiceFields({service,values,set,ar,errors,labels,segments,setSegments,nights}:{service:Service;values:Values;set:(n:string,v:FieldValue)=>void;ar:boolean;errors:Errors;labels:Record<string,string>;segments:Segment[];setSegments:React.Dispatch<React.SetStateAction<Segment[]>>;nights:number}) {
 const o=(rows:[string,string,string][])=>opts(ar,rows); const trip=o([['oneway','One way','ذهاب فقط'],['round','Round trip','ذهاب وعودة'],['multi','Multi-city','عدة مدن']]); const stars=o([['3','3 Star','3 نجوم'],['4','4 Star','4 نجوم'],['5','5 Star','5 نجوم'],['none','No preference','بدون تفضيل']]);
 if(service==='flight') return <><SectionHeading index="01" title={ar?'خط السير':'Route & schedule'}/><Choice name="tripType" label={ar?'نوع الرحلة':'Trip type'} value={values.tripType} set={set} options={trip}/>{values.tripType==='multi'?<div className={styles.full}>{segments.map((s,i)=><div className={styles.segment} key={i}><b>{ar?`الرحلة ${i+1}`:`Flight ${i+1}`}</b><input aria-label={labels.origin} placeholder={labels.origin} value={s.from} onChange={e=>setSegments(x=>x.map((v,j)=>j===i?{...v,from:e.target.value}:v))}/><input aria-label={labels.destination} placeholder={labels.destination} value={s.to} onChange={e=>setSegments(x=>x.map((v,j)=>j===i?{...v,to:e.target.value}:v))}/><input aria-label={labels.departureDate} type="date" min={new Date().toISOString().slice(0,10)} value={s.date} onChange={e=>setSegments(x=>x.map((v,j)=>j===i?{...v,date:e.target.value}:v))}/>{i>1&&<button type="button" onClick={()=>setSegments(x=>x.filter((_,j)=>j!==i))}>{ar?'حذف':'Remove'}</button>}</div>)}{errors.segments&&<small className={styles.error}>{errors.segments}</small>}<button type="button" className={styles.add} onClick={()=>setSegments(x=>[...x,{from:'',to:'',date:''}])}>{ar?'+ إضافة رحلة':'+ Add another flight'}</button></div>:<><Field name="origin" label={labels.origin} value={values.origin} set={set} error={errors.origin}/><Field name="destination" label={labels.destination} value={values.destination} set={set} error={errors.destination}/><Field name="departureDate" type="date" label={labels.departureDate} value={values.departureDate} set={set} error={errors.departureDate}/>{values.tripType==='round'&&<Field name="returnDate" type="date" label={labels.returnDate} value={values.returnDate} set={set} error={errors.returnDate}/>}</>}<TravelerFields {...{values,set,ar,labels}}/><Select name="cabin" label={ar?'درجة السفر':'Cabin class'} value={values.cabin} set={set} options={o([['economy','Economy','السياحية'],['premium','Premium Economy','السياحية الممتازة'],['business','Business','رجال الأعمال'],['first','First','الأولى']])}/><Field name="airline" label={`${ar?'شركة الطيران المفضلة':'Preferred airline'} — ${ar?'اختياري':'Optional'}`} value={values.airline} set={set}/><Toggle name="directOnly" label={ar?'رحلات مباشرة فقط':'Direct flights only'} value={values.directOnly} set={set}/><Toggle name="flexible" label={ar?'التواريخ مرنة':'Flexible dates'} value={values.flexible} set={set}/>{values.flexible&&<Select name="flexRange" label={ar?'هامش المرونة':'Date flexibility'} value={values.flexRange} set={set} options={o([['1','±1 day','± يوم'],['2','±2 days','± يومين'],['3','±3 days','± 3 أيام']])}/>}<Field name="baggage" label={`${ar?'متطلبات الأمتعة':'Baggage requirements'} — ${ar?'اختياري':'Optional'}`} value={values.baggage} set={set}/><TextArea name="notes" label={ar?'ملاحظات أو طلبات خاصة':'Special requests or notes'} value={values.notes} set={set}/></>
 if(service==='hotel') return <><SectionHeading index="01" title={ar?'الإقامة المطلوبة':'Stay requirements'} note={nights?`${nights} ${ar?'ليالٍ':'nights'}`:undefined}/><Field name="hotelDestination" label={ar?'المدينة أو الوجهة':'City / destination'} value={values.hotelDestination} set={set} error={errors.hotelDestination}/><Field name="hotelName" label={`${ar?'اسم الفندق':'Hotel name'} — ${ar?'اختياري':'Optional'}`} value={values.hotelName} set={set}/><Field name="checkIn" type="date" label={ar?'تاريخ الدخول':'Check-in date'} value={values.checkIn} set={set} error={errors.checkIn}/><Field name="checkOut" type="date" label={ar?'تاريخ الخروج':'Check-out date'} value={values.checkOut} set={set} error={errors.checkOut}/><NumberField name="rooms" label={ar?'عدد الغرف':'Rooms'} value={values.rooms} set={set} min={1}/><TravelerFields {...{values,set,ar,labels}}/><Select name="roomType" label={ar?'نوع الغرفة':'Room preference'} value={values.roomType} set={set} options={o([['single','Single','مفردة'],['double','Double','مزدوجة'],['twin','Twin','سريران'],['triple','Triple','ثلاثية'],['family','Family','عائلية'],['suite','Suite','جناح'],['none','No preference','بدون تفضيل']])}/><Select name="category" label={ar?'تصنيف الفندق':'Hotel category'} value={values.category} set={set} options={stars}/><Select name="board" label={ar?'نظام الوجبات':'Board basis'} value={values.board} set={set} options={o([['room','Room only','غرفة فقط'],['breakfast','Bed & breakfast','إفطار'],['half','Half board','نصف إقامة'],['full','Full board','إقامة كاملة'],['all','All inclusive','شامل'],['none','No preference','بدون تفضيل']])}/><Field name="area" label={`${ar?'الحي أو المنطقة المفضلة':'Preferred area / district'} — ${ar?'اختياري':'Optional'}`} value={values.area} set={set}/><Field name="budget" type="number" label={`${ar?'الميزانية لكل ليلة':'Budget per night'} — ${ar?'اختياري':'Optional'}`} value={values.budget} set={set}/><Field name="currency" label={ar?'العملة':'Currency'} value={values.currency} set={set}/><TextArea name="notes" label={ar?'الدخول المبكر أو الغرف المتصلة أو أي متطلبات أخرى':'Early check-in, connecting rooms, accessibility or other requests'} value={values.notes} set={set}/></>
 if(service==='visa') return <><SectionHeading index="01" title={ar?'بيانات طلب التأشيرة':'Visa request details'}/><Field name="visaCountry" label={ar?'دولة التأشيرة':'Visa country / destination'} value={values.visaCountry} set={set} error={errors.visaCountry}/><Field name="nationality" label={ar?'الجنسية':'Nationality'} value={values.nationality} set={set} error={errors.nationality}/><Field name="residence" label={ar?'دولة الإقامة':'Country of residence'} value={values.residence} set={set} error={errors.residence}/><Select name="visaType" label={ar?'نوع التأشيرة':'Visa type'} value={values.visaType} set={set} options={o([['tourist','Tourist','سياحية'],['business','Business','أعمال'],['visit','Visit','زيارة'],['transit','Transit','عبور'],['other','Other','أخرى']])}/><Field name="travelDate" type="date" label={ar?'تاريخ السفر المتوقع':'Expected travel date'} value={values.travelDate} set={set} error={errors.travelDate}/><Field name="returnDate" type="date" label={ar?'تاريخ العودة المتوقع':'Expected return date'} value={values.returnDate} set={set} error={errors.returnDate}/><NumberField name="applicants" label={ar?'عدد المتقدمين':'Number of applicants'} value={values.applicants||1} set={set} min={1}/><Field name="passportExpiry" type="date" label={`${ar?'تاريخ انتهاء الجواز':'Passport expiry'} — ${ar?'اختياري':'Optional'}`} value={values.passportExpiry} set={set}/><Select name="visaStatus" label={ar?'حالة الطلب السابقة':'Existing status'} value={values.visaStatus} set={set} options={o([['first','First-time applicant','أول طلب'],['previous','Previous visa','تأشيرة سابقة'],['valid','Existing valid visa','تأشيرة سارية']])}/><TextArea name="purpose" label={ar?'غرض السفر والتفاصيل':'Purpose of travel and details'} value={values.purpose} set={set}/><p className={styles.notice}>{copy[ar?'ar':'en'].disclaimer}</p></>
 if(service==='umrah') return <><SectionHeading index="01" title={ar?'تفاصيل البرنامج':'Program details'}/><Choice name="programType" label={ar?'نوع البرنامج':'Program type'} value={values.programType} set={set} options={o([['umrah','Umrah','عمرة'],['hajj','Hajj','حج']])}/><Field name="departureCity" label={ar?'مدينة المغادرة':'Preferred departure city'} value={values.departureCity} set={set} error={errors.departureCity}/><Field name="travelDate" type="date" label={ar?'تاريخ السفر المفضل':'Preferred travel date'} value={values.travelDate} set={set} error={errors.travelDate}/><Toggle name="flexible" label={ar?'التواريخ مرنة':'Flexible dates'} value={values.flexible} set={set}/><Field name="duration" label={ar?'المدة المفضلة':'Preferred duration'} value={values.duration} set={set}/><TravelerFields {...{values,set,ar,labels}}/><Select name="makkahCategory" label={ar?'تصنيف فندق مكة':'Makkah hotel preference'} value={values.makkahCategory} set={set} options={stars}/><Select name="madinahCategory" label={ar?'تصنيف فندق المدينة':'Madinah hotel preference'} value={values.madinahCategory} set={set} options={stars}/><Select name="roomType" label={ar?'نوع الغرفة':'Room type'} value={values.roomType} set={set} options={o([['double','Double','مزدوجة'],['triple','Triple','ثلاثية'],['quad','Quad','رباعية'],['family','Family','عائلية'],['other','Other','أخرى']])}/><Select name="packageType" label={ar?'الخدمات المطلوبة':'Package requirement'} value={values.packageType} set={set} options={o([['complete','Complete package','باقة كاملة'],['hotels','Hotels only','فنادق فقط'],['flight-hotel','Flights + hotels','طيران وفنادق'],['ground','Ground services','خدمات أرضية'],['custom','Custom package','باقة مخصصة']])}/>{values.packageType!=='hotels'&&<Toggle name="flightsRequired" label={ar?'الطيران مطلوب':'Flights required'} value={values.flightsRequired} set={set}/>}<Toggle name="airportTransfer" label={ar?'انتقالات المطار مطلوبة':'Airport transfers required'} value={values.airportTransfer} set={set}/><Toggle name="intercity" label={ar?'تنقل بين مكة والمدينة':'Intercity transportation required'} value={values.intercity} set={set}/><NumberField name="makkahNights" label={ar?'ليالي مكة':'Nights in Makkah'} value={values.makkahNights} set={set}/><NumberField name="madinahNights" label={ar?'ليالي المدينة':'Nights in Madinah'} value={values.madinahNights} set={set}/><TextArea name="notes" label={ar?'متطلبات خاصة أو ملاحظات':'Special requirements or notes'} value={values.notes} set={set}/></>
 if(service==='transfer') { const airport=String(values.transferType).includes('airport'); return <><SectionHeading index="01" title={ar?'تفاصيل الانتقال':'Transfer details'}/><Select name="transferType" label={ar?'نوع الانتقال':'Transfer type'} value={values.transferType} set={set} options={o([['airport-hotel','Airport → Hotel','المطار ← الفندق'],['hotel-airport','Hotel → Airport','الفندق ← المطار'],['airport-airport','Airport → Airport','مطار ← مطار'],['hotel-hotel','Hotel → Hotel','فندق ← فندق'],['intercity','Intercity','بين المدن'],['custom','Custom transfer','انتقال مخصص']])}/><Field name="pickup" label={ar?'موقع الاستلام':'Pickup location'} value={values.pickup} set={set} error={errors.pickup}/><Field name="dropoff" label={ar?'الوجهة':'Drop-off destination'} value={values.dropoff} set={set} error={errors.dropoff}/><Field name="pickupDate" type="date" label={ar?'تاريخ الاستلام':'Pickup date'} value={values.pickupDate} set={set} error={errors.pickupDate}/><Field name="pickupTime" type="time" label={ar?'وقت الاستلام':'Pickup time'} value={values.pickupTime} set={set} error={errors.pickupTime}/>{airport&&<><Field name="flightNumber" label={`${ar?'رقم الرحلة':'Flight number'} — ${ar?'اختياري':'Optional'}`} value={values.flightNumber} set={set}/><Field name="flightTime" type="time" label={ar?'موعد الوصول أو المغادرة':'Arrival / departure time'} value={values.flightTime} set={set}/></>}<TravelerFields {...{values,set,ar,labels}}/><Select name="vehicle" label={ar?'نوع المركبة':'Vehicle'} value={values.vehicle} set={set} options={o([['sedan','Sedan','سيدان'],['suv','SUV','دفع رباعي'],['van','Van','فان'],['minibus','Minibus','ميني باص'],['bus','Bus','حافلة'],['luxury','Luxury vehicle','مركبة فاخرة'],['none','No preference','بدون تفضيل']])}/><NumberField name="bags" label={ar?'عدد الحقائب التقريبي':'Approximate bags'} value={values.bags} set={set}/><TextArea name="notes" label={ar?'مقعد طفل أو استقبال أو متطلبات خاصة':'Child seat, meet & greet, accessibility or other needs'} value={values.notes} set={set}/></> }
 return <><SectionHeading index="01" title={ar?'ملخص الرحلة':'Trip outline'}/><Field name="customDestination" label={ar?'الوجهة أو الدول':'Destination / countries'} value={values.customDestination} set={set} error={errors.customDestination}/><Field name="startDate" type="date" label={ar?'تاريخ البداية المفضل':'Preferred start date'} value={values.startDate} set={set} error={errors.startDate}/><Field name="endDate" type="date" label={ar?'تاريخ النهاية المفضل':'Preferred end date'} value={values.endDate} set={set} error={errors.endDate}/><Toggle name="flexible" label={ar?'التواريخ مرنة':'Flexible dates'} value={values.flexible} set={set}/><TravelerFields {...{values,set,ar,labels}}/><Field name="servicesNeeded" label={ar?'الخدمات المطلوبة (مثال: طيران، فنادق، انتقالات)':'Services needed (for example flights, hotels, transfers)'} value={values.servicesNeeded} set={set}/><Select name="tripPurpose" label={ar?'غرض الرحلة':'Trip purpose'} value={values.tripPurpose} set={set} options={o([['leisure','Leisure','سياحة'],['business','Business','أعمال'],['group','Group','مجموعة'],['event','Event','فعالية'],['corporate','Corporate','شركات'],['religious','Religious travel','سفر ديني'],['other','Other','أخرى']])}/><Field name="budget" type="number" label={`${ar?'الميزانية التقديرية':'Estimated budget'} — ${ar?'اختياري':'Optional'}`} value={values.budget} set={set}/><Field name="currency" label={ar?'العملة':'Currency'} value={values.currency} set={set}/><TextArea name="tripBrief" label={ar?'اكتب ما تحتاجه وسيساعدك فريقنا في ترتيب الطلب':'Tell us what you need and our team will help structure the request'} value={values.tripBrief} set={set} error={errors.tripBrief}/></>
}
function TravelerFields({values,set,ar,labels}:{values:Values;set:(n:string,v:FieldValue)=>void;ar:boolean;labels:Record<string,string>}) { return <><SectionHeading index="02" title={ar?'المسافرون':'Travelers'}/><NumberField name="adults" label={labels.adults} value={values.adults} set={set} min={1}/><NumberField name="children" label={labels.children} value={values.children} set={set}/><NumberField name="infants" label={labels.infants} value={values.infants} set={set}/>{Number(values.children)>0&&<Field name="childAges" label={ar?'أعمار الأطفال (افصل بينها بفاصلة)':'Children ages (comma separated)'} value={values.childAges} set={set}/>}</> }
function TextArea({name,label,value,set,error}:{name:string;label:string;value:unknown;set:(n:string,v:string)=>void;error?:string}) { return <label className={`${styles.field} ${styles.full}`}><span>{label}</span><textarea rows={5} value={String(value??'')} onChange={e=>set(name,e.target.value)} aria-invalid={!!error}/>{error&&<small>{error}</small>}</label> }
function Review({service,values,segments,ar,labels,onDetails,onContact,result}:{service:Service;values:Values;segments:Segment[];ar:boolean;labels:Record<string,string>;onDetails:()=>void;onContact:()=>void;result:RequestResult | null}) { const selected=services.find(s=>s.id===service)!; const ignored=new Set(['website','contactMethod','fullName','company','email','phone','residenceCountry']); const rows=Object.entries(values).filter(([k,v])=>!ignored.has(k)&&v!==''&&v!==false&&v!==0&&v!=null).slice(0,14); return <div className={styles.review}><div className={styles.reviewTitle}><span>{ar?'نوع الطلب':'REQUEST TYPE'}</span><h3>{ar?selected.ar:selected.en}</h3></div><div className={styles.reviewGrid}><section><header><b>{ar?'تفاصيل السفر':'Travel details'}</b><button onClick={onDetails}>{ar?'تعديل':'Edit'}</button></header>{values.tripType==='multi'&&segments.map((x,i)=><p key={i}><strong>{i+1}</strong><span dir="ltr">{x.from} → {x.to} · {x.date}</span></p>)}{rows.map(([k,v])=><p key={k}><strong>{labels[k]||humanize(k)}</strong><span>{v===true?(ar?'نعم':'Yes'):String(v)}</span></p>)}</section><section><header><b>{ar?'بيانات التواصل':'Contact'}</b><button onClick={onContact}>{ar?'تعديل':'Edit'}</button></header>{['fullName','company','email','phone','residenceCountry','contactMethod'].map(k=>values[k]?<p key={k}><strong>{labels[k]||humanize(k)}</strong><span dir={k==='email'||k==='phone'?'ltr':undefined}>{String(values[k])}</span></p>:null)}</section></div>{result?.ok===false&&<div className={styles.submitError}>{result.message}</div>}</div> }
const opts=(ar:boolean, rows:[string,string,string][])=>rows.map(([v,en,a])=>[v,ar?a:en] as [string,string]); const pick=(o:Values,keys:string[])=>Object.fromEntries(keys.map(k=>[k,o[k]??''])); const humanize=(s:string)=>s.replace(/([A-Z])/g,' $1').replace(/^./,m=>m.toUpperCase());
function fieldLabels(ar:boolean):Record<string,string>{return ar?{origin:'مدينة أو مطار المغادرة',destination:'مدينة أو مطار الوصول',departureDate:'تاريخ المغادرة',returnDate:'تاريخ العودة',adults:'البالغون',children:'الأطفال',infants:'الرضّع',fullName:'الاسم الكامل',company:'اسم الشركة',email:'البريد الإلكتروني',phone:'رقم الجوال أو واتساب',residenceCountry:'دولة الإقامة',contactMethod:'طريقة التواصل المفضلة'}:{origin:'Departure city / airport',destination:'Destination city / airport',departureDate:'Departure date',returnDate:'Return date',adults:'Adults',children:'Children',infants:'Infants',fullName:'Full name',company:'Company name',email:'Email address',phone:'Mobile / WhatsApp number',residenceCountry:'Country of residence',contactMethod:'Preferred contact method'}}
