'use client'
import Link from 'next/link'
import { ArrowLeft, ArrowRight } from 'lucide-react'
import { PageShell } from '@/components/site'
import { useContent, useLocale } from '@/components/i18n'
import { experienceCopy, solutionSlugs } from '@/components/experience-content'

export default function SolutionsPage(){const{locale}=useLocale();const ar=locale==='ar';const c=experienceCopy[locale].solutions;const common=useContent();const Arrow=ar?ArrowLeft:ArrowRight;return <PageShell>
 <section className="solutions-hero xp-solutions-hero" dir={ar?'rtl':'ltr'}><div className="internal-hero-layout section-shell"><div className="internal-hero-title-col"><div className="section-kicker light">{c.heroKicker}</div><h1>{c.heroTitle}</h1></div><div className="internal-hero-desc-col"><p>{c.heroBody}</p></div></div></section>
 <nav className="xp-service-nav section-shell" aria-label={c.navigator} dir={ar?'rtl':'ltr'}><span>{c.navigator}</span>{common.services.map(([name],i)=><Link href={`#${solutionSlugs[i]}`} key={name}>0{i+1} {name}</Link>)}</nav>
 <section className="xp-service-operations section-shell" dir={ar?'rtl':'ltr'}><div className="xp-section-heading"><div className="section-kicker">01 / SERVICE BRIEFS</div><h2>{c.sectionIntro}</h2></div>{solutionSlugs.slice(0,5).map((slug,i)=><article id={slug} key={slug}><div><span>0{i+1}</span><h3>{common.services[i][0]}</h3><p>{common.services[i][1]}</p></div><div><b>{ar?'نحتاج منك':'WHAT WE NEED'}</b><p>{serviceNeeds[locale][i]}</p></div><div><b>{ar?'نرتّب':'WE HANDLE'}</b><p>{serviceHandle[locale][i]}</p></div><Link href={`/solutions/${slug}`}>{ar?'شوف تفاصيل الخدمة':'Explore the service'}<Arrow size={16}/></Link></article>)}</section>
 <section id="groups-special-requests" className="xp-group-operation section-shell" dir={ar?'rtl':'ltr'}><div><div className="section-kicker light">06 / GROUPS</div><h2>{c.groupsTitle}</h2><p>{c.groupsBody}</p><Link href="/solutions/groups-special-requests" className="button button-gold">{ar?'شاركنا تفاصيل المجموعة':'Discuss a group'}<Arrow size={17}/></Link></div><ol>{c.groupFlow.map((x,i)=><li key={x}><span>0{i+1}</span><strong>{x}</strong></li>)}</ol></section>
 <section id="corporate-travel" className="xp-corporate-split section-shell" dir={ar?'rtl':'ltr'}><div className="section-kicker">07 / CORPORATE</div><h2>{c.corporateTitle}</h2><p>{c.corporateBody}</p><Link href="/solutions/corporate-travel">{ar?'شوف سفر الشركات':'See corporate travel'}<Arrow size={16}/></Link></section>
 <section id="hospitality-solutions" className="xp-hospitality-line section-shell" dir={ar?'rtl':'ltr'}><div><div className="section-kicker">08 / HOSPITALITY</div><h2>{c.hospitalityTitle}</h2></div><div><p>{c.hospitalityBody}</p><Link href="/solutions/hospitality-solutions">{ar?'ناقش تعاون الضيافة':'Discuss hospitality cooperation'}<Arrow size={16}/></Link></div></section>
 <section className="xp-final-cta section-shell" dir={ar?'rtl':'ltr'}><div><div className="section-kicker light">REQUEST</div><h2>{c.finalTitle}</h2><p>{c.finalBody}</p></div><Link href="/contact" className="button button-gold">{c.finalCta}<Arrow size={17}/></Link></section>
</PageShell>}

const serviceNeeds={en:['Destination, dates, rooms, occupancy and meal plan.','Routing, dates, passenger details and timing.','Flight details, pickup points, passengers and vehicle needs.','Rental dates, locations, vehicle category and driver details.','Destination, group size, timing and private/shared preference.'],ar:['الوجهة والتواريخ والغرف والإشغال والوجبات.','خط السير والتواريخ وبيانات المسافرين والمواعيد.','تفاصيل الرحلة ونقاط الاستلام وعدد المسافرين والمركبة.','تواريخ الإيجار والمواقع وفئة السيارة وبيانات السائق.','الوجهة وعدد المشاركين والموعد ونوع التجربة.']} as const
const serviceHandle={en:['Property review, availability, room terms and confirmation.','Schedule review, routing, fares and confirmed itinerary.','Driver, vehicle, airport timing and movement schedule.','Vehicle sourcing, rental terms and pickup confirmation.','Activity options, guides, timing and itinerary alignment.'],ar:['مراجعة المنشآت والتوفر وشروط الغرف والتأكيد.','مراجعة الجداول والمسار والأسعار وتأكيد الرحلة.','السائق والمركبة ومواعيد المطار وجدول التنقل.','توفير السيارة وشروط الإيجار وتأكيد الاستلام.','خيارات الأنشطة والمرشدين والمواعيد وربطها بالبرنامج.']} as const
