'use client'
import Link from 'next/link'
import { ArrowLeft, ArrowRight, BriefcaseBusiness, Building2, CalendarCheck2, Cpu, Handshake, Hotel, MapPinned, Network, PlaneTakeoff, UsersRound } from 'lucide-react'
import { PageShell, images } from '@/components/site'
import { useLocale } from '@/components/i18n'
import { experienceCopy } from '@/components/experience-content'
import { useWebsiteImage } from '@/lib/website-media'

const partnerIcons=[PlaneTakeoff,MapPinned,Building2,BriefcaseBusiness,Hotel,Network]
const matrixIcons=[CalendarCheck2,UsersRound,Handshake,Cpu]

export default function PartnersPage(){const{locale}=useLocale();const ar=locale==='ar';const c=experienceCopy[locale].partners;const Arrow=ar?ArrowLeft:ArrowRight;const heroImage=useWebsiteImage('partners_hero',images.meeting);const mafairjetsImage=useWebsiteImage('partners_network_mafairjets','/partnership/mafairjets.jpg');const tarteebImage=useWebsiteImage('partners_network_tarteeb','/partnership/tarteeb.jpg');const taxidiaImage=useWebsiteImage('partners_network_taxidia','/partnership/taxidia.jpg');const modelsImage=useWebsiteImage('partners_models','/real%20requests.png');const scenariosImage=useWebsiteImage('partners_scenarios','/taxidia02.png');const networkImages=[mafairjetsImage,tarteebImage,taxidiaImage];return <PageShell>
 <section className="partners-hero" dir={ar?'rtl':'ltr'}><div className="partners-hero-image-layer"><img src={heroImage} alt=""/><div className="partners-hero-overlay"/></div><div className="internal-hero-layout section-shell"><div className="internal-hero-title-col"><div className="section-kicker light">{c.heroKicker}</div><h1>{c.heroTitle}</h1></div><div className="internal-hero-desc-col"><p>{c.heroBody}</p></div></div></section>
 <section className="xp-partner-map section-shell" dir={ar?'rtl':'ltr'}><div className="xp-partner-map-intro"><div className="section-kicker">{ar?'٠١ / العلاقات':'01 / RELATIONSHIPS'}</div><h2>{c.whoTitle}</h2><span aria-hidden="true">06</span></div><div className="xp-partner-map-grid">{c.who.map((x,i)=>{const Icon=partnerIcons[i];return <article key={x}><div><b>{ar?['٠١','٠٢','٠٣','٠٤','٠٥','٠٦'][i]:`0${i+1}`}</b><Icon aria-hidden="true"/></div><h3>{x}</h3><i aria-hidden="true"/></article>})}</div></section>
 <section className="xp-partnership-network section-shell" dir={ar?'rtl':'ltr'}><div className="xp-partnership-network-head"><div><div className="section-kicker">{ar?'شبكة الشراكات':'PARTNERSHIP NETWORK'}</div><h2>{c.networkTitle}</h2></div><p>{c.networkBody}</p></div><div className="xp-partnership-logos">{[['MA Fairjets'],['Tarteeb Private'],['Taxidia']].map(([name],i)=><article key={name}><div className="xp-partnership-logo"><img src={networkImages[i]} alt={name}/></div><div><span>{ar?['٠١','٠٢','٠٣'][i]:`0${i+1}`}</span><h3>{name}</h3><p>{c.networkTypes[i]}</p></div></article>)}</div></section>
 <div className="editorial-band editorial-band-navy"><section className="xp-models section-shell" dir={ar?'rtl':'ltr'}><img className="xp-models-art" src={modelsImage} alt="" aria-hidden="true"/><div className="xp-section-heading"><div className="section-kicker light">02 / MODELS</div><h2>{c.modelsTitle}</h2></div><div>{c.models.map(([t,b],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{b}</p></article>)}</div></section></div>
 <section className="xp-matrix section-shell" dir={ar?'rtl':'ltr'}><div className="xp-matrix-heading"><div className="section-kicker">{ar?'٠٣ / نطاق الشراكة':'03 / SCOPE'}</div><h2>{c.matrixTitle}</h2></div><div className="xp-matrix-grid">{c.matrixRows.map((r,i)=>{const Icon=matrixIcons[i];return <article key={r[0]}><header><span>{ar?['٠١','٠٢','٠٣','٠٤'][i]:`0${i+1}`}</span><Icon aria-hidden="true"/></header><h3>{r[0]}</h3><div className="xp-matrix-route"><b>{r[1]}</b><i aria-hidden="true"><em/><em/><em/></i><b>{r[2]}</b></div></article>})}</div></section>
 <section className="xp-onboarding section-shell" dir={ar?'rtl':'ltr'}><div className="xp-onboarding-heading"><div className="section-kicker">{ar?'٠٤ / البداية':'04 / START'}</div><h2>{c.startTitle}</h2></div><ol>{c.start.map((x,i)=><li key={x}><span>{ar?['٠١','٠٢','٠٣','٠٤','٠٥'][i]:`0${i+1}`}</span><strong><b>{x}</b><small>{c.startDescriptions[i]}</small></strong><i aria-hidden="true"/></li>)}</ol></section>
 <section className="xp-scenarios section-shell" dir={ar?'rtl':'ltr'}><div className="xp-scenarios-hero"><div className="xp-section-heading"><div className="section-kicker light">{ar?'٠٥ / حالات العمل':'05 / SCENARIOS'}</div><h2>{c.scenariosTitle}</h2></div><div className="xp-scenarios-visual"><img src={scenariosImage} alt={ar?'واجهة إدارة طلب السفر في تاكسيديا':'Taxidia trip request interface'}/><span>{ar?'طلب واضح':'CLEAR REQUEST'}</span></div></div><div className="xp-scenarios-grid">{c.scenarios.map(([t,b],i)=><article key={t}><span>{ar?['٠١','٠٢','٠٣','٠٤'][i]:`0${i+1}`}</span><h3>{t}</h3><p>{b}</p><i aria-hidden="true"/></article>)}</div></section>
 <div className="editorial-band editorial-band-navy"><section className="xp-bridge section-shell" dir={ar?'rtl':'ltr'}><div><div className="section-kicker light">06 / TECHNOLOGY</div><h2>{c.platformTitle}</h2><p>{c.platformBody}</p></div><Link href="/platform" className="button button-gold">{c.platformCta}<Arrow size={17}/></Link></section></div>
 <section className="xp-partner-cta section-shell" dir={ar?'rtl':'ltr'}><h2>{c.finalTitle}</h2><Link href="/contact" className="button button-navy">{c.finalCta}<Arrow size={17}/></Link></section>
</PageShell>}
